# Generated by Django 5.2.4 on 2025-08-04 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examenes', '0003_user_ya_presento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtemas', to='examenes.subject')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('explicacion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('articulo', 'Artículo')], max_length=50)),
                ('enlace', models.URLField(blank=True, null=True)),
                ('visto', models.BooleanField(default=False)),
                ('subtema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='study.subtema')),
            ],
        ),
    ]
