# Generated by Django 5.2.4 on 2025-07-28 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('puntuacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('opcion_a', models.CharField(max_length=255)),
                ('opcion_b', models.CharField(max_length=255)),
                ('opcion_c', models.CharField(max_length=255)),
                ('opcion_d', models.CharField(max_length=255)),
                ('respuesta_correcta', models.CharField(choices=[('A', 'Opción A'), ('B', 'Opción B'), ('C', 'Opción C'), ('D', 'Opción D')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('colegio', models.CharField(blank=True, max_length=100)),
                ('grado', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_usuario', models.CharField(choices=[('A', 'Opción A'), ('B', 'Opción B'), ('C', 'Opción C'), ('D', 'Opción D')], max_length=1)),
                ('es_correcta', models.BooleanField(default=False)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenes.exam')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenes.question')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='preguntas',
            field=models.ManyToManyField(through='examenes.Answer', to='examenes.question'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenes.category')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenes.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenes.user'),
        ),
    ]
