# Generated by Django 5.2.4 on 2025-07-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name_plural': 'Respuestas'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name_plural': 'Examenes'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Usuarios'},
        ),
    ]
