# Generated by Django 5.2.4 on 2025-07-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0002_alter_answer_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ya_presento',
            field=models.BooleanField(default=False),
        ),
    ]
